name: dtree
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  riverpod: ^0.14.0
  flutter_riverpod: ^0.14.0
  font_awesome_flutter: ^9.1.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_secure_storage: ^5.0.3
  flutter_lints: ^3.0.0
flutter:
  assets:
    - assets/logo1.png
  uses-material-design: true
